package dev.tolana.projectcalculationtool.enums;

public enum Permission {
    ORG_CREATE,
    ORG_DELETE,
    ORG_READ,
    ORG_EDIT,
    ORG_KICK,
    ORG_INVITE,
    DEPT_CREATE,
    DEPT_DELETE,
    DEPT_READ,
    DEPT_EDIT,
    DEPT_KICK,
    DEPT_INVITE,
    TEAM_CREATE,
    TEAM_DELETE,
    TEAM_READ,
    TEAM_EDIT,
    TEAM_KICK,
    TEAM_INVITE,
    PROJECT_CREATE,
    PROJECT_DELETE,
    PROJECT_READ,
    PROJECT_EDIT,
    PROJECT_KICK,
    PROJECT_INVITE,
    TASK_CREATE,
    TASK_DELETE,
    TASK_READ,
    TASK_EDIT,
    TASK_KICK,
    TASK_INVITE
}
